# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nestcc/projects/cFile/Tohka-programming-language

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nestcc/projects/cFile/Tohka-programming-language

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nestcc/projects/cFile/Tohka-programming-language/CMakeFiles /Users/nestcc/projects/cFile/Tohka-programming-language//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nestcc/projects/cFile/Tohka-programming-language/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named toh

# Build rule for target.
toh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 toh
.PHONY : toh

# fast build rule for target.
toh/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/build
.PHONY : toh/fast

client/cli.o: client/cli.cpp.o

.PHONY : client/cli.o

# target to build an object file
client/cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/client/cli.cpp.o
.PHONY : client/cli.cpp.o

client/cli.i: client/cli.cpp.i

.PHONY : client/cli.i

# target to preprocess a source file
client/cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/client/cli.cpp.i
.PHONY : client/cli.cpp.i

client/cli.s: client/cli.cpp.s

.PHONY : client/cli.s

# target to generate assembly for a file
client/cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/client/cli.cpp.s
.PHONY : client/cli.cpp.s

includes/unicode.o: includes/unicode.cpp.o

.PHONY : includes/unicode.o

# target to build an object file
includes/unicode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/includes/unicode.cpp.o
.PHONY : includes/unicode.cpp.o

includes/unicode.i: includes/unicode.cpp.i

.PHONY : includes/unicode.i

# target to preprocess a source file
includes/unicode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/includes/unicode.cpp.i
.PHONY : includes/unicode.cpp.i

includes/unicode.s: includes/unicode.cpp.s

.PHONY : includes/unicode.s

# target to generate assembly for a file
includes/unicode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/includes/unicode.cpp.s
.PHONY : includes/unicode.cpp.s

includes/utils.o: includes/utils.cpp.o

.PHONY : includes/utils.o

# target to build an object file
includes/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/includes/utils.cpp.o
.PHONY : includes/utils.cpp.o

includes/utils.i: includes/utils.cpp.i

.PHONY : includes/utils.i

# target to preprocess a source file
includes/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/includes/utils.cpp.i
.PHONY : includes/utils.cpp.i

includes/utils.s: includes/utils.cpp.s

.PHONY : includes/utils.s

# target to generate assembly for a file
includes/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/includes/utils.cpp.s
.PHONY : includes/utils.cpp.s

object/Frame.o: object/Frame.cpp.o

.PHONY : object/Frame.o

# target to build an object file
object/Frame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/Frame.cpp.o
.PHONY : object/Frame.cpp.o

object/Frame.i: object/Frame.cpp.i

.PHONY : object/Frame.i

# target to preprocess a source file
object/Frame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/Frame.cpp.i
.PHONY : object/Frame.cpp.i

object/Frame.s: object/Frame.cpp.s

.PHONY : object/Frame.s

# target to generate assembly for a file
object/Frame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/Frame.cpp.s
.PHONY : object/Frame.cpp.s

object/ObjClosure.o: object/ObjClosure.cpp.o

.PHONY : object/ObjClosure.o

# target to build an object file
object/ObjClosure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjClosure.cpp.o
.PHONY : object/ObjClosure.cpp.o

object/ObjClosure.i: object/ObjClosure.cpp.i

.PHONY : object/ObjClosure.i

# target to preprocess a source file
object/ObjClosure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjClosure.cpp.i
.PHONY : object/ObjClosure.cpp.i

object/ObjClosure.s: object/ObjClosure.cpp.s

.PHONY : object/ObjClosure.s

# target to generate assembly for a file
object/ObjClosure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjClosure.cpp.s
.PHONY : object/ObjClosure.cpp.s

object/ObjFunction.o: object/ObjFunction.cpp.o

.PHONY : object/ObjFunction.o

# target to build an object file
object/ObjFunction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjFunction.cpp.o
.PHONY : object/ObjFunction.cpp.o

object/ObjFunction.i: object/ObjFunction.cpp.i

.PHONY : object/ObjFunction.i

# target to preprocess a source file
object/ObjFunction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjFunction.cpp.i
.PHONY : object/ObjFunction.cpp.i

object/ObjFunction.s: object/ObjFunction.cpp.s

.PHONY : object/ObjFunction.s

# target to generate assembly for a file
object/ObjFunction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjFunction.cpp.s
.PHONY : object/ObjFunction.cpp.s

object/ObjInstance.o: object/ObjInstance.cpp.o

.PHONY : object/ObjInstance.o

# target to build an object file
object/ObjInstance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjInstance.cpp.o
.PHONY : object/ObjInstance.cpp.o

object/ObjInstance.i: object/ObjInstance.cpp.i

.PHONY : object/ObjInstance.i

# target to preprocess a source file
object/ObjInstance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjInstance.cpp.i
.PHONY : object/ObjInstance.cpp.i

object/ObjInstance.s: object/ObjInstance.cpp.s

.PHONY : object/ObjInstance.s

# target to generate assembly for a file
object/ObjInstance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjInstance.cpp.s
.PHONY : object/ObjInstance.cpp.s

object/ObjList.o: object/ObjList.cpp.o

.PHONY : object/ObjList.o

# target to build an object file
object/ObjList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjList.cpp.o
.PHONY : object/ObjList.cpp.o

object/ObjList.i: object/ObjList.cpp.i

.PHONY : object/ObjList.i

# target to preprocess a source file
object/ObjList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjList.cpp.i
.PHONY : object/ObjList.cpp.i

object/ObjList.s: object/ObjList.cpp.s

.PHONY : object/ObjList.s

# target to generate assembly for a file
object/ObjList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjList.cpp.s
.PHONY : object/ObjList.cpp.s

object/ObjModule.o: object/ObjModule.cpp.o

.PHONY : object/ObjModule.o

# target to build an object file
object/ObjModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjModule.cpp.o
.PHONY : object/ObjModule.cpp.o

object/ObjModule.i: object/ObjModule.cpp.i

.PHONY : object/ObjModule.i

# target to preprocess a source file
object/ObjModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjModule.cpp.i
.PHONY : object/ObjModule.cpp.i

object/ObjModule.s: object/ObjModule.cpp.s

.PHONY : object/ObjModule.s

# target to generate assembly for a file
object/ObjModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjModule.cpp.s
.PHONY : object/ObjModule.cpp.s

object/ObjString.o: object/ObjString.cpp.o

.PHONY : object/ObjString.o

# target to build an object file
object/ObjString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjString.cpp.o
.PHONY : object/ObjString.cpp.o

object/ObjString.i: object/ObjString.cpp.i

.PHONY : object/ObjString.i

# target to preprocess a source file
object/ObjString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjString.cpp.i
.PHONY : object/ObjString.cpp.i

object/ObjString.s: object/ObjString.cpp.s

.PHONY : object/ObjString.s

# target to generate assembly for a file
object/ObjString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjString.cpp.s
.PHONY : object/ObjString.cpp.s

object/ObjUpvalue.o: object/ObjUpvalue.cpp.o

.PHONY : object/ObjUpvalue.o

# target to build an object file
object/ObjUpvalue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjUpvalue.cpp.o
.PHONY : object/ObjUpvalue.cpp.o

object/ObjUpvalue.i: object/ObjUpvalue.cpp.i

.PHONY : object/ObjUpvalue.i

# target to preprocess a source file
object/ObjUpvalue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjUpvalue.cpp.i
.PHONY : object/ObjUpvalue.cpp.i

object/ObjUpvalue.s: object/ObjUpvalue.cpp.s

.PHONY : object/ObjUpvalue.s

# target to generate assembly for a file
object/ObjUpvalue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjUpvalue.cpp.s
.PHONY : object/ObjUpvalue.cpp.s

object/ObjectHeader.o: object/ObjectHeader.cpp.o

.PHONY : object/ObjectHeader.o

# target to build an object file
object/ObjectHeader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjectHeader.cpp.o
.PHONY : object/ObjectHeader.cpp.o

object/ObjectHeader.i: object/ObjectHeader.cpp.i

.PHONY : object/ObjectHeader.i

# target to preprocess a source file
object/ObjectHeader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjectHeader.cpp.i
.PHONY : object/ObjectHeader.cpp.i

object/ObjectHeader.s: object/ObjectHeader.cpp.s

.PHONY : object/ObjectHeader.s

# target to generate assembly for a file
object/ObjectHeader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/ObjectHeader.cpp.s
.PHONY : object/ObjectHeader.cpp.s

object/Value.o: object/Value.cpp.o

.PHONY : object/Value.o

# target to build an object file
object/Value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/Value.cpp.o
.PHONY : object/Value.cpp.o

object/Value.i: object/Value.cpp.i

.PHONY : object/Value.i

# target to preprocess a source file
object/Value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/Value.cpp.i
.PHONY : object/Value.cpp.i

object/Value.s: object/Value.cpp.s

.PHONY : object/Value.s

# target to generate assembly for a file
object/Value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/object/Value.cpp.s
.PHONY : object/Value.cpp.s

parser/parser.o: parser/parser.cpp.o

.PHONY : parser/parser.o

# target to build an object file
parser/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/parser/parser.cpp.o
.PHONY : parser/parser.cpp.o

parser/parser.i: parser/parser.cpp.i

.PHONY : parser/parser.i

# target to preprocess a source file
parser/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/parser/parser.cpp.i
.PHONY : parser/parser.cpp.i

parser/parser.s: parser/parser.cpp.s

.PHONY : parser/parser.s

# target to generate assembly for a file
parser/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/parser/parser.cpp.s
.PHONY : parser/parser.cpp.s

vm/core.o: vm/core.cpp.o

.PHONY : vm/core.o

# target to build an object file
vm/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/vm/core.cpp.o
.PHONY : vm/core.cpp.o

vm/core.i: vm/core.cpp.i

.PHONY : vm/core.i

# target to preprocess a source file
vm/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/vm/core.cpp.i
.PHONY : vm/core.cpp.i

vm/core.s: vm/core.cpp.s

.PHONY : vm/core.s

# target to generate assembly for a file
vm/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/vm/core.cpp.s
.PHONY : vm/core.cpp.s

vm/vm.o: vm/vm.cpp.o

.PHONY : vm/vm.o

# target to build an object file
vm/vm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/vm/vm.cpp.o
.PHONY : vm/vm.cpp.o

vm/vm.i: vm/vm.cpp.i

.PHONY : vm/vm.i

# target to preprocess a source file
vm/vm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/vm/vm.cpp.i
.PHONY : vm/vm.cpp.i

vm/vm.s: vm/vm.cpp.s

.PHONY : vm/vm.s

# target to generate assembly for a file
vm/vm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toh.dir/build.make CMakeFiles/toh.dir/vm/vm.cpp.s
.PHONY : vm/vm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... toh"
	@echo "... client/cli.o"
	@echo "... client/cli.i"
	@echo "... client/cli.s"
	@echo "... includes/unicode.o"
	@echo "... includes/unicode.i"
	@echo "... includes/unicode.s"
	@echo "... includes/utils.o"
	@echo "... includes/utils.i"
	@echo "... includes/utils.s"
	@echo "... object/Frame.o"
	@echo "... object/Frame.i"
	@echo "... object/Frame.s"
	@echo "... object/ObjClosure.o"
	@echo "... object/ObjClosure.i"
	@echo "... object/ObjClosure.s"
	@echo "... object/ObjFunction.o"
	@echo "... object/ObjFunction.i"
	@echo "... object/ObjFunction.s"
	@echo "... object/ObjInstance.o"
	@echo "... object/ObjInstance.i"
	@echo "... object/ObjInstance.s"
	@echo "... object/ObjList.o"
	@echo "... object/ObjList.i"
	@echo "... object/ObjList.s"
	@echo "... object/ObjModule.o"
	@echo "... object/ObjModule.i"
	@echo "... object/ObjModule.s"
	@echo "... object/ObjString.o"
	@echo "... object/ObjString.i"
	@echo "... object/ObjString.s"
	@echo "... object/ObjUpvalue.o"
	@echo "... object/ObjUpvalue.i"
	@echo "... object/ObjUpvalue.s"
	@echo "... object/ObjectHeader.o"
	@echo "... object/ObjectHeader.i"
	@echo "... object/ObjectHeader.s"
	@echo "... object/Value.o"
	@echo "... object/Value.i"
	@echo "... object/Value.s"
	@echo "... parser/parser.o"
	@echo "... parser/parser.i"
	@echo "... parser/parser.s"
	@echo "... vm/core.o"
	@echo "... vm/core.i"
	@echo "... vm/core.s"
	@echo "... vm/vm.o"
	@echo "... vm/vm.i"
	@echo "... vm/vm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

